### ISSUE TITLE
Fix Warn

### ISSUE THREAD

**Issue by danielguaycha** [fullstackreact/google-maps-react#410] opened 2020-01-22 17:09 UTC
I get a warning in the browser when using the hoc `GoogleApiWrapper` 
## Warn
````js 
react-dom.development.js:12357 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Wrapper
````

## React.js versions
````json
{
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
}
````
![warn](https://user-images.githubusercontent.com/15874126/72916365-e9878d00-3d0f-11ea-9c31-2b4cdc3bdae3.png)

**Comment by FredrikAugust** [comment] 2020-01-29 14:48
Duplicate of #376.

**Closed** 2024-02-21 03:13 UTC
